language: python
notifications:
  email:
    recipients:
      - 379978424@qq.com
    on_success: always # default: change
    on_failure: always # default: always
matrix:
  include:
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell

before_install:
  - pip3 install --upgrade pip
  - pip3 install -r app/requirements.txt
  - pip3 install -r test/requirements.txt
script:
  - sh test.sh
after_success:
  cd test && codecov

