image:
  - macos

stack: python 3

install:
  - "pip install -r app/requirements.txt"
  - cd test
  - "pip install -r requirements.txt"
build: off

test_script:
  - "nosetests --with-coverage --cover-package app --cover-package test && cd .. && flake8 --exclude build --max-line-length 89 --ignore=F401"
